[//]: # (DO NOT EDIT index.md. index.md is generated by nbpages. Make changes to templates/index.md.tpl.)
# {{ page_title }}

This seminar course explores modern topics in computation, data analytics, and
modeling relevant for engineering and the chemical sciences. Ph.D. students in engineering,
science, and mathematics are the intended audience. Each meeting, 1 or more enrolled students
will (co-)lead the discussion on chapters in the semester text. The goal of these discussions is not
to lecture on the material, but instead present a working example that highlights a core concept or
method from each chapter.

For Summer 2020, we are studying [*Uncertainty Quantification and Predictive Computational Science*](https://onesearch.library.nd.edu/permalink/f/1phik6l/ndu_aleph005207583) by Prof. Ryan McClarren.

{% for line in readme_toc -%}
{{ line }}
{% endfor %}


